
# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application-dev.yml file.
# ===================================================================
server:
  port: 7080


spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/events
        name:
        username: root
        password: root
        test-while-idle: true
        validationQuery: SELECT 1
    jpa:
#        database-platform: org.hibernate.dialect.MariaDB53Dialect
#        database: MARIADB
        show_sql: false
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.event.merge.entity_copy_observer: allow
            hibernate.format_sql: false
            hibernate.use_sql_comments: false
        hibernate:
          ddl-auto: none



flyway:
  baseline-on-migrate: true
  validate-on-migrate: false
  locations:
    - db/migration
  enabled: true




event:
  swagger:
    title: Code once  talents application
    description: Code once Talents Core
    version: 0.1.0
    termsOfServiceUrl:
    contactName:
    contactUrl:
    contactEmail:
    license:
    licenseUrl:
  oauth2:
    client_id: mMKBdsIgpC9prxBwgd6V
    client_secret: QzNmrG57pQpt5B9azA01
    grant_type: password #authorization_code,refresh_token,password,implicit
    scope: read # read,write
    token_validity: 3600
    refresh_token_validity: 3600
    jwt_key: I8opCRdidwqvG6F7xqGQ
    url : http://localhost:9080
  mail:
    from : mmarzougui@event.fr
    adminEmail: admin@gmail.com

